apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: grade-rate-limit
 namespace: grade-demo
 annotations:
  kubernetes.io/ingress.class: kong
config:
 minute: 5
 limit_by: consumer
 policy: local
plugin: rate-limiting