apiVersion: v1
kind: Secret
metadata:
  name: grade-jwt-credential
  namespace: grade-demo
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  kongCredType: jwt
  key: "grade-submission-issuer"
  algorithm: "HS256"
  secret: "grade-super-secret-jwt-signing-key-replace-in-production-min32chars"
