apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: grade-jwt
  namespace: grade-demo
  annotations:
    kubernetes.io/ingress.class: kong
plugin: jwt
config:
  key_claim_name: iss
  claims_to_verify:
    - exp
  header_names:
    - Authorization
  uri_param_names: []
  cookie_names: []
  run_on_preflight: true
  maximum_expiration: 3600
